# .github/workflows/terraform-deploy.yml
name: Terraform and EKS Deployment

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # Use inline credentials with Terraform commands
      - name: Terraform Init
        run: |
          AWS_ACCESS_KEY_ID="ASIAXGSGVPD76XGZI2FC" \
          AWS_SECRET_ACCESS_KEY="MP5ZgyjXsMn48Chc7LlNt4NkukHfVW3SfVJQVHbT" \
          terraform init

      - name: Terraform Plan
        run: |
          AWS_ACCESS_KEY_ID="ASIAXGSGVPD76XGZI2FC" \
          AWS_SECRET_ACCESS_KEY="MP5ZgyjXsMn48Chc7LlNt4NkukHfVW3SfVJQVHbT" \
          terraform plan

      - name: Terraform Apply
        run: |
          AWS_ACCESS_KEY_ID="ASIAXGSGVPD76XGZI2FC" \
          AWS_SECRET_ACCESS_KEY="MP5ZgyjXsMn48Chc7LlNt4NkukHfVW3SfVJQVHbT" \
          terraform apply -auto-approve

  deploy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.25.0'

      # Use inline credentials for EKS and kubectl commands
      - name: Configure kubectl
        run: |
          AWS_ACCESS_KEY_ID="ASIAXGSGVPD76XGZI2FC" \
          AWS_SECRET_ACCESS_KEY="MP5ZgyjXsMn48Chc7LlNt4NkukHfVW3SfVJQVHbT" \
          aws eks --region us-east-2 update-kubeconfig --name education-eks-zdJJOm4M

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
